Restore support for setting null as a tag value (Resolves #823)
jaegertracing/jaeger-client-java pull request #824
Opened 2022-01-03 12:44 UTC by amirhadadi

To maintain backwards compatibility, we better restore the ability to set null as a tag value.
This change reverts the use of `ConcurrentHashMap` for the tags map in `JaegerSpan` back to `HashMap`, as `HashMap` supports null values while `ConcurrentHashMap` does not.

2022-01-03 15:35 UTC, yurishkuro requested changes
Jaeger backend does not support null values for tags. I agree we should fix the NPE, but I'd fix it but removing the key from the map.

2022-01-03 21:35 UTC, amirhadadi commented
> Jaeger backend does not support null values for tags. I agree we should fix the NPE, but I'd fix it but removing the key from the map.

@yurishkuro I looked at usages of `JaegerSpan::getTags`.
One usage is in [`JaegerThriftSpanConverter`](https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/reporters/protocols/JaegerThriftSpanConverter.java#L57). It ends up calling [`String.valueOf(tagValue)`](https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/reporters/protocols/JaegerThriftSpanConverter.java#L126) converting null to "null", so it seems it will succeed in sending the tag.
Same thing goes for [`ThriftSpanConverter`](https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-zipkin/src/main/java/io/jaegertracing/zipkin/internal/ThriftSpanConverter.java#L90).

[`V2SpanConverter`](https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-zipkin/src/main/java/io/jaegertracing/zipkin/internal/V2SpanConverter.java#L117) OTOH would fail with NPE when calling `tagValue.toString()`.

So removing null values from the map would be a breaking change, depending on how spans are being converted.

2022-01-03 22:34 UTC, yurishkuro commented
> V2SpanConverter OTOH would fail with NPE when calling tagValue.toString()

So the null check I am suggesting will fix this.

2022-01-03 23:30 UTC, amirhadadi commented
> > V2SpanConverter OTOH would fail with NPE when calling tagValue.toString()
> 
> So the null check I am suggesting will fix this.

@yurishkuro yes, and that's good, but my main point is what I wrote before that about `ThriftSpanConverter` and `JaegerThriftSpanConverter`. They use `String.valueOf(value)` instead of `value.toString()`.
Since `String.valueOf(null)` == `"null"`, the tag value is sent correctly when it's null.
So now we will be changing that behavior and the tag with "null" as value won't be sent anymore.

2022-01-03 23:47 UTC, yurishkuro commented
We can make the null check add a string value "null", ie push this conversion higher in the stack to the sdk instead of the reporter

2022-01-04 06:27 UTC, amirhadadi commented
@yurishkuro done.

2022-01-04 15:07 UTC, yurishkuro approved these changes

2022-01-04 15:07 UTC, merged